/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ActivateStrategyRequest } from '../models';
// @ts-ignore
import type { CommandEnvelopeResponse } from '../models';
// @ts-ignore
import type { CommandStatusResponse } from '../models';
// @ts-ignore
import type { CreateStrategyRequest } from '../models';
// @ts-ignore
import type { DeactivateStrategyRequest } from '../models';
// @ts-ignore
import type { DisableExecutionRequest } from '../models';
// @ts-ignore
import type { EnableExecutionRequest } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { ExecutionStateResponse } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { HealthResponse } from '../models';
// @ts-ignore
import type { LiveStrategiesResponse } from '../models';
// @ts-ignore
import type { StrategiesResponse } from '../models';
// @ts-ignore
import type { StrategyResponse } from '../models';
// @ts-ignore
import type { StrategyTypeResponse } from '../models';
// @ts-ignore
import type { StrategyTypesResponse } from '../models';
// @ts-ignore
import type { UpdateStrategyRequest } from '../models';
// @ts-ignore
import type { ValidateStrategyConfigRequest } from '../models';
// @ts-ignore
import type { ValidateStrategyConfigResponse } from '../models';
// @ts-ignore
import type { VersionConflictResponse } from '../models';
/**
 * ControlApi - axios parameter creator
 */
export const ControlApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Activate strategy for live trading (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id.
         * @summary Activate Strategy
         * @param {string} strategyId 
         * @param {ActivateStrategyRequest} activateStrategyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePost: async (strategyId: string, activateStrategyRequest: ActivateStrategyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'strategyId' is not null or undefined
            assertParamExists('activateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePost', 'strategyId', strategyId)
            // verify required parameter 'activateStrategyRequest' is not null or undefined
            assertParamExists('activateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePost', 'activateStrategyRequest', activateStrategyRequest)
            const localVarPath = `/api/v1/commands/live-strategies/{strategy_id}/activate`
                .replace(`{${"strategy_id"}}`, encodeURIComponent(String(strategyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(activateStrategyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new strategy in registry.  Per Commit 17: This endpoint now: - Resolves version selector to exact version - Validates config before creation - Calculates config_hash for reproducibility - Generates deployment_id for correlation - Adds reproducibility metadata (run_identity)
         * @summary Create Strategy
         * @param {CreateStrategyRequest} createStrategyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStrategyApiV1CommandsStrategiesPost: async (createStrategyRequest: CreateStrategyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createStrategyRequest' is not null or undefined
            assertParamExists('createStrategyApiV1CommandsStrategiesPost', 'createStrategyRequest', createStrategyRequest)
            const localVarPath = `/api/v1/commands/strategies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createStrategyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deactivate strategy for live trading (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id.
         * @summary Deactivate Strategy
         * @param {string} strategyId 
         * @param {DeactivateStrategyRequest} deactivateStrategyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePost: async (strategyId: string, deactivateStrategyRequest: DeactivateStrategyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'strategyId' is not null or undefined
            assertParamExists('deactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePost', 'strategyId', strategyId)
            // verify required parameter 'deactivateStrategyRequest' is not null or undefined
            assertParamExists('deactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePost', 'deactivateStrategyRequest', deactivateStrategyRequest)
            const localVarPath = `/api/v1/commands/live-strategies/{strategy_id}/deactivate`
                .replace(`{${"strategy_id"}}`, encodeURIComponent(String(strategyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deactivateStrategyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Disable execution (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id. Version check: If expected_version != current version, returns 409 Conflict.
         * @summary Disable Execution
         * @param {DisableExecutionRequest} disableExecutionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disableExecutionApiV1CommandsExecutionDisablePost: async (disableExecutionRequest: DisableExecutionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'disableExecutionRequest' is not null or undefined
            assertParamExists('disableExecutionApiV1CommandsExecutionDisablePost', 'disableExecutionRequest', disableExecutionRequest)
            const localVarPath = `/api/v1/commands/execution/disable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(disableExecutionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enable execution (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id. Version check: If expected_version != current version, returns 409 Conflict.
         * @summary Enable Execution
         * @param {EnableExecutionRequest} enableExecutionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        enableExecutionApiV1CommandsExecutionEnablePost: async (enableExecutionRequest: EnableExecutionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'enableExecutionRequest' is not null or undefined
            assertParamExists('enableExecutionApiV1CommandsExecutionEnablePost', 'enableExecutionRequest', enableExecutionRequest)
            const localVarPath = `/api/v1/commands/execution/enable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(enableExecutionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get command status by command_id.
         * @summary Get Command Status
         * @param {string} commandId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommandStatusApiV1StateCommandsCommandIdGet: async (commandId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commandId' is not null or undefined
            assertParamExists('getCommandStatusApiV1StateCommandsCommandIdGet', 'commandId', commandId)
            const localVarPath = `/api/v1/state/commands/{command_id}`
                .replace(`{${"command_id"}}`, encodeURIComponent(String(commandId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get execution control state (with version for optimistic concurrency).
         * @summary Get Execution State
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutionStateApiV1StateExecutionGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/state/execution`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get system health with individual gate statuses.  Returns overall status and individual gate statuses (db, market_data_freshness, etc.). Overall status = worst gate status (down > degraded > ok).  Note: Health gates implementation is basic in this commit. Full health gate checks will be implemented in later commits.
         * @summary Get Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHealthApiV1StateHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/state/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get active live strategies.
         * @summary Get Live Strategies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLiveStrategiesApiV1StateLiveStrategiesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/state/live-strategies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all strategies in registry.
         * @summary Get Strategies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStrategiesApiV1StateStrategiesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/state/strategies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get details for a specific strategy template type.  Per Commit 15: Returns template information including all available versions and parameter schema.  Args:     type_id: Template type identifier (e.g., \"simple_threshold\")  Returns:     StrategyTypeResponse with template details  Raises:     HTTPException: 404 if template type not found
         * @summary Get Strategy Template
         * @param {string} typeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGet: async (typeId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'typeId' is not null or undefined
            assertParamExists('getStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGet', 'typeId', typeId)
            const localVarPath = `/api/v1/state/strategies/templates/{type_id}`
                .replace(`{${"type_id"}}`, encodeURIComponent(String(typeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get details for a specific strategy template version.  Per Commit 15: Returns template information for a specific version including parameter schema.  Args:     type_id: Template type identifier (e.g., \"simple_threshold\")     version: Template version (e.g., \"1.0.0\")  Returns:     StrategyTypeResponse with template details (single version in available_versions)  Raises:     HTTPException: 404 if template version not found
         * @summary Get Strategy Template Version
         * @param {string} typeId 
         * @param {string} version 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGet: async (typeId: string, version: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'typeId' is not null or undefined
            assertParamExists('getStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGet', 'typeId', typeId)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('getStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGet', 'version', version)
            const localVarPath = `/api/v1/state/strategies/templates/{type_id}/versions/{version}`
                .replace(`{${"type_id"}}`, encodeURIComponent(String(typeId)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all available strategy templates.  Per Commit 15: Template discovery endpoint for clients to discover available strategy types and their versions.  Returns:     StrategyTypesResponse with list of all registered templates
         * @summary List Strategy Templates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listStrategyTemplatesApiV1StateStrategiesTemplatesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/state/strategies/templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an existing strategy in registry.
         * @summary Update Strategy
         * @param {string} strategyId 
         * @param {UpdateStrategyRequest} updateStrategyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStrategyApiV1CommandsStrategiesStrategyIdPatch: async (strategyId: string, updateStrategyRequest: UpdateStrategyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'strategyId' is not null or undefined
            assertParamExists('updateStrategyApiV1CommandsStrategiesStrategyIdPatch', 'strategyId', strategyId)
            // verify required parameter 'updateStrategyRequest' is not null or undefined
            assertParamExists('updateStrategyApiV1CommandsStrategiesStrategyIdPatch', 'updateStrategyRequest', updateStrategyRequest)
            const localVarPath = `/api/v1/commands/strategies/{strategy_id}`
                .replace(`{${"strategy_id"}}`, encodeURIComponent(String(strategyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateStrategyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Validate a strategy configuration against a template schema.  Per Commit 16: This endpoint allows clients to validate configurations before creating strategy instances. Returns validation results with clear error messages.  Args:     request: Validation request with template_type_id, version_selector, and config  Returns:     ValidateStrategyConfigResponse with validation results  Raises:     HTTPException: 400 if template not found or version resolution fails
         * @summary Validate Strategy Config
         * @param {ValidateStrategyConfigRequest} validateStrategyConfigRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateStrategyConfigApiV1StateStrategiesValidatePost: async (validateStrategyConfigRequest: ValidateStrategyConfigRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'validateStrategyConfigRequest' is not null or undefined
            assertParamExists('validateStrategyConfigApiV1StateStrategiesValidatePost', 'validateStrategyConfigRequest', validateStrategyConfigRequest)
            const localVarPath = `/api/v1/state/strategies/validate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(validateStrategyConfigRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ControlApi - functional programming interface
 */
export const ControlApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ControlApiAxiosParamCreator(configuration)
    return {
        /**
         * Activate strategy for live trading (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id.
         * @summary Activate Strategy
         * @param {string} strategyId 
         * @param {ActivateStrategyRequest} activateStrategyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePost(strategyId: string, activateStrategyRequest: ActivateStrategyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommandEnvelopeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePost(strategyId, activateStrategyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.activateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new strategy in registry.  Per Commit 17: This endpoint now: - Resolves version selector to exact version - Validates config before creation - Calculates config_hash for reproducibility - Generates deployment_id for correlation - Adds reproducibility metadata (run_identity)
         * @summary Create Strategy
         * @param {CreateStrategyRequest} createStrategyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createStrategyApiV1CommandsStrategiesPost(createStrategyRequest: CreateStrategyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StrategyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createStrategyApiV1CommandsStrategiesPost(createStrategyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.createStrategyApiV1CommandsStrategiesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deactivate strategy for live trading (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id.
         * @summary Deactivate Strategy
         * @param {string} strategyId 
         * @param {DeactivateStrategyRequest} deactivateStrategyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePost(strategyId: string, deactivateStrategyRequest: DeactivateStrategyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommandEnvelopeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePost(strategyId, deactivateStrategyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.deactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Disable execution (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id. Version check: If expected_version != current version, returns 409 Conflict.
         * @summary Disable Execution
         * @param {DisableExecutionRequest} disableExecutionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async disableExecutionApiV1CommandsExecutionDisablePost(disableExecutionRequest: DisableExecutionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommandEnvelopeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.disableExecutionApiV1CommandsExecutionDisablePost(disableExecutionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.disableExecutionApiV1CommandsExecutionDisablePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Enable execution (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id. Version check: If expected_version != current version, returns 409 Conflict.
         * @summary Enable Execution
         * @param {EnableExecutionRequest} enableExecutionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async enableExecutionApiV1CommandsExecutionEnablePost(enableExecutionRequest: EnableExecutionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommandEnvelopeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.enableExecutionApiV1CommandsExecutionEnablePost(enableExecutionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.enableExecutionApiV1CommandsExecutionEnablePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get command status by command_id.
         * @summary Get Command Status
         * @param {string} commandId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCommandStatusApiV1StateCommandsCommandIdGet(commandId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommandStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCommandStatusApiV1StateCommandsCommandIdGet(commandId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.getCommandStatusApiV1StateCommandsCommandIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get execution control state (with version for optimistic concurrency).
         * @summary Get Execution State
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExecutionStateApiV1StateExecutionGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExecutionStateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExecutionStateApiV1StateExecutionGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.getExecutionStateApiV1StateExecutionGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get system health with individual gate statuses.  Returns overall status and individual gate statuses (db, market_data_freshness, etc.). Overall status = worst gate status (down > degraded > ok).  Note: Health gates implementation is basic in this commit. Full health gate checks will be implemented in later commits.
         * @summary Get Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHealthApiV1StateHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHealthApiV1StateHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.getHealthApiV1StateHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get active live strategies.
         * @summary Get Live Strategies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLiveStrategiesApiV1StateLiveStrategiesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LiveStrategiesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLiveStrategiesApiV1StateLiveStrategiesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.getLiveStrategiesApiV1StateLiveStrategiesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all strategies in registry.
         * @summary Get Strategies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStrategiesApiV1StateStrategiesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StrategiesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStrategiesApiV1StateStrategiesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.getStrategiesApiV1StateStrategiesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get details for a specific strategy template type.  Per Commit 15: Returns template information including all available versions and parameter schema.  Args:     type_id: Template type identifier (e.g., \"simple_threshold\")  Returns:     StrategyTypeResponse with template details  Raises:     HTTPException: 404 if template type not found
         * @summary Get Strategy Template
         * @param {string} typeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGet(typeId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StrategyTypeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGet(typeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.getStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get details for a specific strategy template version.  Per Commit 15: Returns template information for a specific version including parameter schema.  Args:     type_id: Template type identifier (e.g., \"simple_threshold\")     version: Template version (e.g., \"1.0.0\")  Returns:     StrategyTypeResponse with template details (single version in available_versions)  Raises:     HTTPException: 404 if template version not found
         * @summary Get Strategy Template Version
         * @param {string} typeId 
         * @param {string} version 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGet(typeId: string, version: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StrategyTypeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGet(typeId, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.getStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List all available strategy templates.  Per Commit 15: Template discovery endpoint for clients to discover available strategy types and their versions.  Returns:     StrategyTypesResponse with list of all registered templates
         * @summary List Strategy Templates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listStrategyTemplatesApiV1StateStrategiesTemplatesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StrategyTypesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listStrategyTemplatesApiV1StateStrategiesTemplatesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.listStrategyTemplatesApiV1StateStrategiesTemplatesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update an existing strategy in registry.
         * @summary Update Strategy
         * @param {string} strategyId 
         * @param {UpdateStrategyRequest} updateStrategyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStrategyApiV1CommandsStrategiesStrategyIdPatch(strategyId: string, updateStrategyRequest: UpdateStrategyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StrategyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateStrategyApiV1CommandsStrategiesStrategyIdPatch(strategyId, updateStrategyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.updateStrategyApiV1CommandsStrategiesStrategyIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Validate a strategy configuration against a template schema.  Per Commit 16: This endpoint allows clients to validate configurations before creating strategy instances. Returns validation results with clear error messages.  Args:     request: Validation request with template_type_id, version_selector, and config  Returns:     ValidateStrategyConfigResponse with validation results  Raises:     HTTPException: 400 if template not found or version resolution fails
         * @summary Validate Strategy Config
         * @param {ValidateStrategyConfigRequest} validateStrategyConfigRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateStrategyConfigApiV1StateStrategiesValidatePost(validateStrategyConfigRequest: ValidateStrategyConfigRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ValidateStrategyConfigResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateStrategyConfigApiV1StateStrategiesValidatePost(validateStrategyConfigRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ControlApi.validateStrategyConfigApiV1StateStrategiesValidatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ControlApi - factory interface
 */
export const ControlApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ControlApiFp(configuration)
    return {
        /**
         * Activate strategy for live trading (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id.
         * @summary Activate Strategy
         * @param {ControlApiActivateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePost(requestParameters: ControlApiActivateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommandEnvelopeResponse> {
            return localVarFp.activateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePost(requestParameters.strategyId, requestParameters.activateStrategyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new strategy in registry.  Per Commit 17: This endpoint now: - Resolves version selector to exact version - Validates config before creation - Calculates config_hash for reproducibility - Generates deployment_id for correlation - Adds reproducibility metadata (run_identity)
         * @summary Create Strategy
         * @param {ControlApiCreateStrategyApiV1CommandsStrategiesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStrategyApiV1CommandsStrategiesPost(requestParameters: ControlApiCreateStrategyApiV1CommandsStrategiesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<StrategyResponse> {
            return localVarFp.createStrategyApiV1CommandsStrategiesPost(requestParameters.createStrategyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Deactivate strategy for live trading (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id.
         * @summary Deactivate Strategy
         * @param {ControlApiDeactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePost(requestParameters: ControlApiDeactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommandEnvelopeResponse> {
            return localVarFp.deactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePost(requestParameters.strategyId, requestParameters.deactivateStrategyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Disable execution (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id. Version check: If expected_version != current version, returns 409 Conflict.
         * @summary Disable Execution
         * @param {ControlApiDisableExecutionApiV1CommandsExecutionDisablePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disableExecutionApiV1CommandsExecutionDisablePost(requestParameters: ControlApiDisableExecutionApiV1CommandsExecutionDisablePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommandEnvelopeResponse> {
            return localVarFp.disableExecutionApiV1CommandsExecutionDisablePost(requestParameters.disableExecutionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Enable execution (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id. Version check: If expected_version != current version, returns 409 Conflict.
         * @summary Enable Execution
         * @param {ControlApiEnableExecutionApiV1CommandsExecutionEnablePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        enableExecutionApiV1CommandsExecutionEnablePost(requestParameters: ControlApiEnableExecutionApiV1CommandsExecutionEnablePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommandEnvelopeResponse> {
            return localVarFp.enableExecutionApiV1CommandsExecutionEnablePost(requestParameters.enableExecutionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get command status by command_id.
         * @summary Get Command Status
         * @param {ControlApiGetCommandStatusApiV1StateCommandsCommandIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommandStatusApiV1StateCommandsCommandIdGet(requestParameters: ControlApiGetCommandStatusApiV1StateCommandsCommandIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommandStatusResponse> {
            return localVarFp.getCommandStatusApiV1StateCommandsCommandIdGet(requestParameters.commandId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get execution control state (with version for optimistic concurrency).
         * @summary Get Execution State
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutionStateApiV1StateExecutionGet(options?: RawAxiosRequestConfig): AxiosPromise<ExecutionStateResponse> {
            return localVarFp.getExecutionStateApiV1StateExecutionGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get system health with individual gate statuses.  Returns overall status and individual gate statuses (db, market_data_freshness, etc.). Overall status = worst gate status (down > degraded > ok).  Note: Health gates implementation is basic in this commit. Full health gate checks will be implemented in later commits.
         * @summary Get Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHealthApiV1StateHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<HealthResponse> {
            return localVarFp.getHealthApiV1StateHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get active live strategies.
         * @summary Get Live Strategies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLiveStrategiesApiV1StateLiveStrategiesGet(options?: RawAxiosRequestConfig): AxiosPromise<LiveStrategiesResponse> {
            return localVarFp.getLiveStrategiesApiV1StateLiveStrategiesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get all strategies in registry.
         * @summary Get Strategies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStrategiesApiV1StateStrategiesGet(options?: RawAxiosRequestConfig): AxiosPromise<StrategiesResponse> {
            return localVarFp.getStrategiesApiV1StateStrategiesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get details for a specific strategy template type.  Per Commit 15: Returns template information including all available versions and parameter schema.  Args:     type_id: Template type identifier (e.g., \"simple_threshold\")  Returns:     StrategyTypeResponse with template details  Raises:     HTTPException: 404 if template type not found
         * @summary Get Strategy Template
         * @param {ControlApiGetStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGet(requestParameters: ControlApiGetStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<StrategyTypeResponse> {
            return localVarFp.getStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGet(requestParameters.typeId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get details for a specific strategy template version.  Per Commit 15: Returns template information for a specific version including parameter schema.  Args:     type_id: Template type identifier (e.g., \"simple_threshold\")     version: Template version (e.g., \"1.0.0\")  Returns:     StrategyTypeResponse with template details (single version in available_versions)  Raises:     HTTPException: 404 if template version not found
         * @summary Get Strategy Template Version
         * @param {ControlApiGetStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGet(requestParameters: ControlApiGetStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<StrategyTypeResponse> {
            return localVarFp.getStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGet(requestParameters.typeId, requestParameters.version, options).then((request) => request(axios, basePath));
        },
        /**
         * List all available strategy templates.  Per Commit 15: Template discovery endpoint for clients to discover available strategy types and their versions.  Returns:     StrategyTypesResponse with list of all registered templates
         * @summary List Strategy Templates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listStrategyTemplatesApiV1StateStrategiesTemplatesGet(options?: RawAxiosRequestConfig): AxiosPromise<StrategyTypesResponse> {
            return localVarFp.listStrategyTemplatesApiV1StateStrategiesTemplatesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Update an existing strategy in registry.
         * @summary Update Strategy
         * @param {ControlApiUpdateStrategyApiV1CommandsStrategiesStrategyIdPatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStrategyApiV1CommandsStrategiesStrategyIdPatch(requestParameters: ControlApiUpdateStrategyApiV1CommandsStrategiesStrategyIdPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<StrategyResponse> {
            return localVarFp.updateStrategyApiV1CommandsStrategiesStrategyIdPatch(requestParameters.strategyId, requestParameters.updateStrategyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Validate a strategy configuration against a template schema.  Per Commit 16: This endpoint allows clients to validate configurations before creating strategy instances. Returns validation results with clear error messages.  Args:     request: Validation request with template_type_id, version_selector, and config  Returns:     ValidateStrategyConfigResponse with validation results  Raises:     HTTPException: 400 if template not found or version resolution fails
         * @summary Validate Strategy Config
         * @param {ControlApiValidateStrategyConfigApiV1StateStrategiesValidatePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateStrategyConfigApiV1StateStrategiesValidatePost(requestParameters: ControlApiValidateStrategyConfigApiV1StateStrategiesValidatePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ValidateStrategyConfigResponse> {
            return localVarFp.validateStrategyConfigApiV1StateStrategiesValidatePost(requestParameters.validateStrategyConfigRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for activateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePost operation in ControlApi.
 */
export interface ControlApiActivateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePostRequest {
    readonly strategyId: string

    readonly activateStrategyRequest: ActivateStrategyRequest
}

/**
 * Request parameters for createStrategyApiV1CommandsStrategiesPost operation in ControlApi.
 */
export interface ControlApiCreateStrategyApiV1CommandsStrategiesPostRequest {
    readonly createStrategyRequest: CreateStrategyRequest
}

/**
 * Request parameters for deactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePost operation in ControlApi.
 */
export interface ControlApiDeactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePostRequest {
    readonly strategyId: string

    readonly deactivateStrategyRequest: DeactivateStrategyRequest
}

/**
 * Request parameters for disableExecutionApiV1CommandsExecutionDisablePost operation in ControlApi.
 */
export interface ControlApiDisableExecutionApiV1CommandsExecutionDisablePostRequest {
    readonly disableExecutionRequest: DisableExecutionRequest
}

/**
 * Request parameters for enableExecutionApiV1CommandsExecutionEnablePost operation in ControlApi.
 */
export interface ControlApiEnableExecutionApiV1CommandsExecutionEnablePostRequest {
    readonly enableExecutionRequest: EnableExecutionRequest
}

/**
 * Request parameters for getCommandStatusApiV1StateCommandsCommandIdGet operation in ControlApi.
 */
export interface ControlApiGetCommandStatusApiV1StateCommandsCommandIdGetRequest {
    readonly commandId: string
}

/**
 * Request parameters for getStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGet operation in ControlApi.
 */
export interface ControlApiGetStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGetRequest {
    readonly typeId: string
}

/**
 * Request parameters for getStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGet operation in ControlApi.
 */
export interface ControlApiGetStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGetRequest {
    readonly typeId: string

    readonly version: string
}

/**
 * Request parameters for updateStrategyApiV1CommandsStrategiesStrategyIdPatch operation in ControlApi.
 */
export interface ControlApiUpdateStrategyApiV1CommandsStrategiesStrategyIdPatchRequest {
    readonly strategyId: string

    readonly updateStrategyRequest: UpdateStrategyRequest
}

/**
 * Request parameters for validateStrategyConfigApiV1StateStrategiesValidatePost operation in ControlApi.
 */
export interface ControlApiValidateStrategyConfigApiV1StateStrategiesValidatePostRequest {
    readonly validateStrategyConfigRequest: ValidateStrategyConfigRequest
}

/**
 * ControlApi - object-oriented interface
 */
export class ControlApi extends BaseAPI {
    /**
     * Activate strategy for live trading (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id.
     * @summary Activate Strategy
     * @param {ControlApiActivateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public activateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePost(requestParameters: ControlApiActivateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePostRequest, options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).activateStrategyApiV1CommandsLiveStrategiesStrategyIdActivatePost(requestParameters.strategyId, requestParameters.activateStrategyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new strategy in registry.  Per Commit 17: This endpoint now: - Resolves version selector to exact version - Validates config before creation - Calculates config_hash for reproducibility - Generates deployment_id for correlation - Adds reproducibility metadata (run_identity)
     * @summary Create Strategy
     * @param {ControlApiCreateStrategyApiV1CommandsStrategiesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createStrategyApiV1CommandsStrategiesPost(requestParameters: ControlApiCreateStrategyApiV1CommandsStrategiesPostRequest, options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).createStrategyApiV1CommandsStrategiesPost(requestParameters.createStrategyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deactivate strategy for live trading (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id.
     * @summary Deactivate Strategy
     * @param {ControlApiDeactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePost(requestParameters: ControlApiDeactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePostRequest, options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).deactivateStrategyApiV1CommandsLiveStrategiesStrategyIdDeactivatePost(requestParameters.strategyId, requestParameters.deactivateStrategyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Disable execution (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id. Version check: If expected_version != current version, returns 409 Conflict.
     * @summary Disable Execution
     * @param {ControlApiDisableExecutionApiV1CommandsExecutionDisablePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public disableExecutionApiV1CommandsExecutionDisablePost(requestParameters: ControlApiDisableExecutionApiV1CommandsExecutionDisablePostRequest, options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).disableExecutionApiV1CommandsExecutionDisablePost(requestParameters.disableExecutionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Enable execution (creates command in queue).  Idempotent: If client_request_id already exists, returns existing command_id. Version check: If expected_version != current version, returns 409 Conflict.
     * @summary Enable Execution
     * @param {ControlApiEnableExecutionApiV1CommandsExecutionEnablePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public enableExecutionApiV1CommandsExecutionEnablePost(requestParameters: ControlApiEnableExecutionApiV1CommandsExecutionEnablePostRequest, options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).enableExecutionApiV1CommandsExecutionEnablePost(requestParameters.enableExecutionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get command status by command_id.
     * @summary Get Command Status
     * @param {ControlApiGetCommandStatusApiV1StateCommandsCommandIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCommandStatusApiV1StateCommandsCommandIdGet(requestParameters: ControlApiGetCommandStatusApiV1StateCommandsCommandIdGetRequest, options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).getCommandStatusApiV1StateCommandsCommandIdGet(requestParameters.commandId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get execution control state (with version for optimistic concurrency).
     * @summary Get Execution State
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getExecutionStateApiV1StateExecutionGet(options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).getExecutionStateApiV1StateExecutionGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get system health with individual gate statuses.  Returns overall status and individual gate statuses (db, market_data_freshness, etc.). Overall status = worst gate status (down > degraded > ok).  Note: Health gates implementation is basic in this commit. Full health gate checks will be implemented in later commits.
     * @summary Get Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHealthApiV1StateHealthGet(options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).getHealthApiV1StateHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get active live strategies.
     * @summary Get Live Strategies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLiveStrategiesApiV1StateLiveStrategiesGet(options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).getLiveStrategiesApiV1StateLiveStrategiesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all strategies in registry.
     * @summary Get Strategies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStrategiesApiV1StateStrategiesGet(options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).getStrategiesApiV1StateStrategiesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get details for a specific strategy template type.  Per Commit 15: Returns template information including all available versions and parameter schema.  Args:     type_id: Template type identifier (e.g., \"simple_threshold\")  Returns:     StrategyTypeResponse with template details  Raises:     HTTPException: 404 if template type not found
     * @summary Get Strategy Template
     * @param {ControlApiGetStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGet(requestParameters: ControlApiGetStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGetRequest, options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).getStrategyTemplateApiV1StateStrategiesTemplatesTypeIdGet(requestParameters.typeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get details for a specific strategy template version.  Per Commit 15: Returns template information for a specific version including parameter schema.  Args:     type_id: Template type identifier (e.g., \"simple_threshold\")     version: Template version (e.g., \"1.0.0\")  Returns:     StrategyTypeResponse with template details (single version in available_versions)  Raises:     HTTPException: 404 if template version not found
     * @summary Get Strategy Template Version
     * @param {ControlApiGetStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGet(requestParameters: ControlApiGetStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGetRequest, options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).getStrategyTemplateVersionApiV1StateStrategiesTemplatesTypeIdVersionsVersionGet(requestParameters.typeId, requestParameters.version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List all available strategy templates.  Per Commit 15: Template discovery endpoint for clients to discover available strategy types and their versions.  Returns:     StrategyTypesResponse with list of all registered templates
     * @summary List Strategy Templates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listStrategyTemplatesApiV1StateStrategiesTemplatesGet(options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).listStrategyTemplatesApiV1StateStrategiesTemplatesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update an existing strategy in registry.
     * @summary Update Strategy
     * @param {ControlApiUpdateStrategyApiV1CommandsStrategiesStrategyIdPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateStrategyApiV1CommandsStrategiesStrategyIdPatch(requestParameters: ControlApiUpdateStrategyApiV1CommandsStrategiesStrategyIdPatchRequest, options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).updateStrategyApiV1CommandsStrategiesStrategyIdPatch(requestParameters.strategyId, requestParameters.updateStrategyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Validate a strategy configuration against a template schema.  Per Commit 16: This endpoint allows clients to validate configurations before creating strategy instances. Returns validation results with clear error messages.  Args:     request: Validation request with template_type_id, version_selector, and config  Returns:     ValidateStrategyConfigResponse with validation results  Raises:     HTTPException: 400 if template not found or version resolution fails
     * @summary Validate Strategy Config
     * @param {ControlApiValidateStrategyConfigApiV1StateStrategiesValidatePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public validateStrategyConfigApiV1StateStrategiesValidatePost(requestParameters: ControlApiValidateStrategyConfigApiV1StateStrategiesValidatePostRequest, options?: RawAxiosRequestConfig) {
        return ControlApiFp(this.configuration).validateStrategyConfigApiV1StateStrategiesValidatePost(requestParameters.validateStrategyConfigRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

