/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { HistoricalTicksResponse } from '../models';
// @ts-ignore
import type { MarketTickResponse } from '../models';
// @ts-ignore
import type { MarketsResponse } from '../models';
/**
 * MarketApi - axios parameter creator
 */
export const MarketApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get historical ticks for a market/outcome.  Returns a list of market ticks for the specified market and outcome, optionally filtered by time range. Used for charting and historical analysis.  Args:     request: FastAPI request (for correlation ID)     market_slug: Market identifier (e.g., \"btc-updown-15m-1767900600\")     outcome: Market outcome (\"UP\" or \"DOWN\")     from_ts: Start timestamp (inclusive, optional)     to_ts: End timestamp (inclusive, optional)     limit: Maximum number of ticks to return (default: 5000, max: 10000)     repository: MarketTickRepository (injected via FastAPI)  Returns:     HistoricalTicksResponse with list of ticks and count  Raises:     HTTPException: 400 if outcome is invalid, 500 on database error  Note:     - For a 15-minute market window, all ticks should typically fit within the default limit     - Ticks are ordered by ts_wall ascending, ts_mono ascending     - Use from_ts/to_ts to narrow the time range if needed
         * @summary Get Historical Ticks
         * @param {string} marketSlug Market identifier (e.g., \&#39;btc-updown-15m-1767900600\&#39;)
         * @param {string} outcome Market outcome: UP or DOWN
         * @param {string | null} [fromTs] Start timestamp (ISO 8601 UTC, inclusive)
         * @param {string | null} [toTs] End timestamp (ISO 8601 UTC, inclusive)
         * @param {number} [limit] Maximum number of ticks to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistoricalTicksApiV1MarketTicksHistoryGet: async (marketSlug: string, outcome: string, fromTs?: string | null, toTs?: string | null, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'marketSlug' is not null or undefined
            assertParamExists('getHistoricalTicksApiV1MarketTicksHistoryGet', 'marketSlug', marketSlug)
            // verify required parameter 'outcome' is not null or undefined
            assertParamExists('getHistoricalTicksApiV1MarketTicksHistoryGet', 'outcome', outcome)
            const localVarPath = `/api/v1/market/ticks/history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (marketSlug !== undefined) {
                localVarQueryParameter['market_slug'] = marketSlug;
            }

            if (outcome !== undefined) {
                localVarQueryParameter['outcome'] = outcome;
            }

            if (fromTs !== undefined) {
                localVarQueryParameter['from_ts'] = (fromTs as any instanceof Date) ?
                    (fromTs as any).toISOString() :
                    fromTs;
            }

            if (toTs !== undefined) {
                localVarQueryParameter['to_ts'] = (toTs as any instanceof Date) ?
                    (toTs as any).toISOString() :
                    toTs;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get latest tick for a market/outcome.  Returns the most recent market tick for the specified market and outcome. Used for quick price checks and initial UI state.  Args:     request: FastAPI request (for correlation ID)     market_slug: Market identifier (e.g., \"btc-updown-15m-1767900600\")     outcome: Market outcome (\"UP\" or \"DOWN\")     repository: MarketTickRepository (injected via FastAPI)  Returns:     MarketTickResponse with latest tick data  Raises:     HTTPException: 400 if outcome is invalid, 404 if no data found, 500 on database error
         * @summary Get Latest Tick
         * @param {string} marketSlug Market identifier (e.g., \&#39;btc-updown-15m-1767900600\&#39;)
         * @param {string} outcome Market outcome: UP or DOWN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLatestTickApiV1MarketTicksLatestGet: async (marketSlug: string, outcome: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'marketSlug' is not null or undefined
            assertParamExists('getLatestTickApiV1MarketTicksLatestGet', 'marketSlug', marketSlug)
            // verify required parameter 'outcome' is not null or undefined
            assertParamExists('getLatestTickApiV1MarketTicksLatestGet', 'outcome', outcome)
            const localVarPath = `/api/v1/market/ticks/latest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (marketSlug !== undefined) {
                localVarQueryParameter['market_slug'] = marketSlug;
            }

            if (outcome !== undefined) {
                localVarQueryParameter['outcome'] = outcome;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get list of available markets.  Returns a list of all markets with tick data, optionally filtered by pattern and active status. Markets are ordered by latest_tick_ts descending (newest first).  Args:     request: FastAPI request (for correlation ID)     pattern: Market pattern filter (e.g., \"btc-updown-15m\", optional)     active_only: If true, only return active markets (default: false)     repository: MarketTickRepository (injected via FastAPI)  Returns:     MarketsResponse with list of markets and count  Raises:     HTTPException: 500 on database error  Note:     - Markets are ordered by latest_tick_ts descending (newest first)     - Markets with null latest_tick_ts appear last     - Active status is determined by comparing market window start to current window start
         * @summary Get Markets
         * @param {string | null} [pattern] Market pattern filter (e.g., \&#39;btc-updown-15m\&#39;)
         * @param {boolean} [activeOnly] Filter to only active markets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMarketsApiV1MarketMarketsGet: async (pattern?: string | null, activeOnly?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/market/markets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (pattern !== undefined) {
                localVarQueryParameter['pattern'] = pattern;
            }

            if (activeOnly !== undefined) {
                localVarQueryParameter['active_only'] = activeOnly;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MarketApi - functional programming interface
 */
export const MarketApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MarketApiAxiosParamCreator(configuration)
    return {
        /**
         * Get historical ticks for a market/outcome.  Returns a list of market ticks for the specified market and outcome, optionally filtered by time range. Used for charting and historical analysis.  Args:     request: FastAPI request (for correlation ID)     market_slug: Market identifier (e.g., \"btc-updown-15m-1767900600\")     outcome: Market outcome (\"UP\" or \"DOWN\")     from_ts: Start timestamp (inclusive, optional)     to_ts: End timestamp (inclusive, optional)     limit: Maximum number of ticks to return (default: 5000, max: 10000)     repository: MarketTickRepository (injected via FastAPI)  Returns:     HistoricalTicksResponse with list of ticks and count  Raises:     HTTPException: 400 if outcome is invalid, 500 on database error  Note:     - For a 15-minute market window, all ticks should typically fit within the default limit     - Ticks are ordered by ts_wall ascending, ts_mono ascending     - Use from_ts/to_ts to narrow the time range if needed
         * @summary Get Historical Ticks
         * @param {string} marketSlug Market identifier (e.g., \&#39;btc-updown-15m-1767900600\&#39;)
         * @param {string} outcome Market outcome: UP or DOWN
         * @param {string | null} [fromTs] Start timestamp (ISO 8601 UTC, inclusive)
         * @param {string | null} [toTs] End timestamp (ISO 8601 UTC, inclusive)
         * @param {number} [limit] Maximum number of ticks to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHistoricalTicksApiV1MarketTicksHistoryGet(marketSlug: string, outcome: string, fromTs?: string | null, toTs?: string | null, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HistoricalTicksResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHistoricalTicksApiV1MarketTicksHistoryGet(marketSlug, outcome, fromTs, toTs, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MarketApi.getHistoricalTicksApiV1MarketTicksHistoryGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get latest tick for a market/outcome.  Returns the most recent market tick for the specified market and outcome. Used for quick price checks and initial UI state.  Args:     request: FastAPI request (for correlation ID)     market_slug: Market identifier (e.g., \"btc-updown-15m-1767900600\")     outcome: Market outcome (\"UP\" or \"DOWN\")     repository: MarketTickRepository (injected via FastAPI)  Returns:     MarketTickResponse with latest tick data  Raises:     HTTPException: 400 if outcome is invalid, 404 if no data found, 500 on database error
         * @summary Get Latest Tick
         * @param {string} marketSlug Market identifier (e.g., \&#39;btc-updown-15m-1767900600\&#39;)
         * @param {string} outcome Market outcome: UP or DOWN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLatestTickApiV1MarketTicksLatestGet(marketSlug: string, outcome: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MarketTickResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLatestTickApiV1MarketTicksLatestGet(marketSlug, outcome, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MarketApi.getLatestTickApiV1MarketTicksLatestGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get list of available markets.  Returns a list of all markets with tick data, optionally filtered by pattern and active status. Markets are ordered by latest_tick_ts descending (newest first).  Args:     request: FastAPI request (for correlation ID)     pattern: Market pattern filter (e.g., \"btc-updown-15m\", optional)     active_only: If true, only return active markets (default: false)     repository: MarketTickRepository (injected via FastAPI)  Returns:     MarketsResponse with list of markets and count  Raises:     HTTPException: 500 on database error  Note:     - Markets are ordered by latest_tick_ts descending (newest first)     - Markets with null latest_tick_ts appear last     - Active status is determined by comparing market window start to current window start
         * @summary Get Markets
         * @param {string | null} [pattern] Market pattern filter (e.g., \&#39;btc-updown-15m\&#39;)
         * @param {boolean} [activeOnly] Filter to only active markets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMarketsApiV1MarketMarketsGet(pattern?: string | null, activeOnly?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MarketsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMarketsApiV1MarketMarketsGet(pattern, activeOnly, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MarketApi.getMarketsApiV1MarketMarketsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MarketApi - factory interface
 */
export const MarketApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MarketApiFp(configuration)
    return {
        /**
         * Get historical ticks for a market/outcome.  Returns a list of market ticks for the specified market and outcome, optionally filtered by time range. Used for charting and historical analysis.  Args:     request: FastAPI request (for correlation ID)     market_slug: Market identifier (e.g., \"btc-updown-15m-1767900600\")     outcome: Market outcome (\"UP\" or \"DOWN\")     from_ts: Start timestamp (inclusive, optional)     to_ts: End timestamp (inclusive, optional)     limit: Maximum number of ticks to return (default: 5000, max: 10000)     repository: MarketTickRepository (injected via FastAPI)  Returns:     HistoricalTicksResponse with list of ticks and count  Raises:     HTTPException: 400 if outcome is invalid, 500 on database error  Note:     - For a 15-minute market window, all ticks should typically fit within the default limit     - Ticks are ordered by ts_wall ascending, ts_mono ascending     - Use from_ts/to_ts to narrow the time range if needed
         * @summary Get Historical Ticks
         * @param {MarketApiGetHistoricalTicksApiV1MarketTicksHistoryGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistoricalTicksApiV1MarketTicksHistoryGet(requestParameters: MarketApiGetHistoricalTicksApiV1MarketTicksHistoryGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<HistoricalTicksResponse> {
            return localVarFp.getHistoricalTicksApiV1MarketTicksHistoryGet(requestParameters.marketSlug, requestParameters.outcome, requestParameters.fromTs, requestParameters.toTs, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Get latest tick for a market/outcome.  Returns the most recent market tick for the specified market and outcome. Used for quick price checks and initial UI state.  Args:     request: FastAPI request (for correlation ID)     market_slug: Market identifier (e.g., \"btc-updown-15m-1767900600\")     outcome: Market outcome (\"UP\" or \"DOWN\")     repository: MarketTickRepository (injected via FastAPI)  Returns:     MarketTickResponse with latest tick data  Raises:     HTTPException: 400 if outcome is invalid, 404 if no data found, 500 on database error
         * @summary Get Latest Tick
         * @param {MarketApiGetLatestTickApiV1MarketTicksLatestGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLatestTickApiV1MarketTicksLatestGet(requestParameters: MarketApiGetLatestTickApiV1MarketTicksLatestGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<MarketTickResponse> {
            return localVarFp.getLatestTickApiV1MarketTicksLatestGet(requestParameters.marketSlug, requestParameters.outcome, options).then((request) => request(axios, basePath));
        },
        /**
         * Get list of available markets.  Returns a list of all markets with tick data, optionally filtered by pattern and active status. Markets are ordered by latest_tick_ts descending (newest first).  Args:     request: FastAPI request (for correlation ID)     pattern: Market pattern filter (e.g., \"btc-updown-15m\", optional)     active_only: If true, only return active markets (default: false)     repository: MarketTickRepository (injected via FastAPI)  Returns:     MarketsResponse with list of markets and count  Raises:     HTTPException: 500 on database error  Note:     - Markets are ordered by latest_tick_ts descending (newest first)     - Markets with null latest_tick_ts appear last     - Active status is determined by comparing market window start to current window start
         * @summary Get Markets
         * @param {MarketApiGetMarketsApiV1MarketMarketsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMarketsApiV1MarketMarketsGet(requestParameters: MarketApiGetMarketsApiV1MarketMarketsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<MarketsResponse> {
            return localVarFp.getMarketsApiV1MarketMarketsGet(requestParameters.pattern, requestParameters.activeOnly, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getHistoricalTicksApiV1MarketTicksHistoryGet operation in MarketApi.
 */
export interface MarketApiGetHistoricalTicksApiV1MarketTicksHistoryGetRequest {
    /**
     * Market identifier (e.g., \&#39;btc-updown-15m-1767900600\&#39;)
     */
    readonly marketSlug: string

    /**
     * Market outcome: UP or DOWN
     */
    readonly outcome: string

    /**
     * Start timestamp (ISO 8601 UTC, inclusive)
     */
    readonly fromTs?: string | null

    /**
     * End timestamp (ISO 8601 UTC, inclusive)
     */
    readonly toTs?: string | null

    /**
     * Maximum number of ticks to return
     */
    readonly limit?: number
}

/**
 * Request parameters for getLatestTickApiV1MarketTicksLatestGet operation in MarketApi.
 */
export interface MarketApiGetLatestTickApiV1MarketTicksLatestGetRequest {
    /**
     * Market identifier (e.g., \&#39;btc-updown-15m-1767900600\&#39;)
     */
    readonly marketSlug: string

    /**
     * Market outcome: UP or DOWN
     */
    readonly outcome: string
}

/**
 * Request parameters for getMarketsApiV1MarketMarketsGet operation in MarketApi.
 */
export interface MarketApiGetMarketsApiV1MarketMarketsGetRequest {
    /**
     * Market pattern filter (e.g., \&#39;btc-updown-15m\&#39;)
     */
    readonly pattern?: string | null

    /**
     * Filter to only active markets
     */
    readonly activeOnly?: boolean
}

/**
 * MarketApi - object-oriented interface
 */
export class MarketApi extends BaseAPI {
    /**
     * Get historical ticks for a market/outcome.  Returns a list of market ticks for the specified market and outcome, optionally filtered by time range. Used for charting and historical analysis.  Args:     request: FastAPI request (for correlation ID)     market_slug: Market identifier (e.g., \"btc-updown-15m-1767900600\")     outcome: Market outcome (\"UP\" or \"DOWN\")     from_ts: Start timestamp (inclusive, optional)     to_ts: End timestamp (inclusive, optional)     limit: Maximum number of ticks to return (default: 5000, max: 10000)     repository: MarketTickRepository (injected via FastAPI)  Returns:     HistoricalTicksResponse with list of ticks and count  Raises:     HTTPException: 400 if outcome is invalid, 500 on database error  Note:     - For a 15-minute market window, all ticks should typically fit within the default limit     - Ticks are ordered by ts_wall ascending, ts_mono ascending     - Use from_ts/to_ts to narrow the time range if needed
     * @summary Get Historical Ticks
     * @param {MarketApiGetHistoricalTicksApiV1MarketTicksHistoryGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHistoricalTicksApiV1MarketTicksHistoryGet(requestParameters: MarketApiGetHistoricalTicksApiV1MarketTicksHistoryGetRequest, options?: RawAxiosRequestConfig) {
        return MarketApiFp(this.configuration).getHistoricalTicksApiV1MarketTicksHistoryGet(requestParameters.marketSlug, requestParameters.outcome, requestParameters.fromTs, requestParameters.toTs, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get latest tick for a market/outcome.  Returns the most recent market tick for the specified market and outcome. Used for quick price checks and initial UI state.  Args:     request: FastAPI request (for correlation ID)     market_slug: Market identifier (e.g., \"btc-updown-15m-1767900600\")     outcome: Market outcome (\"UP\" or \"DOWN\")     repository: MarketTickRepository (injected via FastAPI)  Returns:     MarketTickResponse with latest tick data  Raises:     HTTPException: 400 if outcome is invalid, 404 if no data found, 500 on database error
     * @summary Get Latest Tick
     * @param {MarketApiGetLatestTickApiV1MarketTicksLatestGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLatestTickApiV1MarketTicksLatestGet(requestParameters: MarketApiGetLatestTickApiV1MarketTicksLatestGetRequest, options?: RawAxiosRequestConfig) {
        return MarketApiFp(this.configuration).getLatestTickApiV1MarketTicksLatestGet(requestParameters.marketSlug, requestParameters.outcome, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get list of available markets.  Returns a list of all markets with tick data, optionally filtered by pattern and active status. Markets are ordered by latest_tick_ts descending (newest first).  Args:     request: FastAPI request (for correlation ID)     pattern: Market pattern filter (e.g., \"btc-updown-15m\", optional)     active_only: If true, only return active markets (default: false)     repository: MarketTickRepository (injected via FastAPI)  Returns:     MarketsResponse with list of markets and count  Raises:     HTTPException: 500 on database error  Note:     - Markets are ordered by latest_tick_ts descending (newest first)     - Markets with null latest_tick_ts appear last     - Active status is determined by comparing market window start to current window start
     * @summary Get Markets
     * @param {MarketApiGetMarketsApiV1MarketMarketsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMarketsApiV1MarketMarketsGet(requestParameters: MarketApiGetMarketsApiV1MarketMarketsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return MarketApiFp(this.configuration).getMarketsApiV1MarketMarketsGet(requestParameters.pattern, requestParameters.activeOnly, options).then((request) => request(this.axios, this.basePath));
    }
}

