"""market tick table

Revision ID: 2544c4bd05f5
Revises: 21bc6d880faf
Create Date: 2026-01-20 21:45:25.707528

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2544c4bd05f5"
down_revision: str | Sequence[str] | None = "21bc6d880faf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create market_ticks table for time-series market data storage.

    This migration creates:
    - Table market_ticks with all columns and constraints
    - Indexes optimized for time-series queries (BRIN on ts_wall, composite on market/outcome/time)
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_ticks",
        sa.Column(
            "tick_id",
            sa.UUID(),
            nullable=False,
            comment="Unique tick identifier (UUID, derived from MarketDataEvent.event_id)",
        ),
        sa.Column(
            "ts_wall",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="Wall-clock time in UTC (partitioning key)",
        ),
        sa.Column(
            "ts_mono", sa.Float(), nullable=False, comment="Monotonic timestamp for ordering"
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Record insertion timestamp",
        ),
        sa.Column("market_slug", sa.Text(), nullable=False, comment="Polymarket market identifier"),
        sa.Column("outcome", sa.Text(), nullable=False, comment="Market outcome: UP or DOWN"),
        sa.Column(
            "best_bid",
            sa.Numeric(precision=18, scale=8),
            nullable=False,
            comment="Best bid price (0-1 range)",
        ),
        sa.Column(
            "best_ask",
            sa.Numeric(precision=18, scale=8),
            nullable=False,
            comment="Best ask price (0-1 range)",
        ),
        sa.Column(
            "mid",
            sa.Numeric(precision=18, scale=8),
            nullable=False,
            comment="Mid-market price: (best_bid + best_ask) / 2",
        ),
        sa.Column(
            "spread",
            sa.Numeric(precision=18, scale=8),
            nullable=False,
            comment="Bid-ask spread: best_ask - best_bid",
        ),
        sa.Column(
            "spread_bps",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
            comment="Spread in basis points: spread * 10000",
        ),
        sa.Column(
            "event_id", sa.UUID(), nullable=True, comment="Reference to events.event_id (nullable)"
        ),
        sa.Column("run_id", sa.Text(), nullable=False, comment="Process run ID for correlation"),
        sa.CheckConstraint("outcome IN ('UP', 'DOWN')", name="market_ticks_outcome_check"),
        sa.CheckConstraint("best_ask >= 0 AND best_ask <= 1", name="market_ticks_best_ask_check"),
        sa.CheckConstraint("best_bid >= 0 AND best_bid <= 1", name="market_ticks_best_bid_check"),
        sa.CheckConstraint("ts_mono >= 0", name="market_ticks_ts_mono_check"),
        sa.PrimaryKeyConstraint("tick_id", "ts_wall"),
    )
    # ### end Alembic commands ###

    # Create indexes optimized for time-series queries
    # 1. BRIN index on ts_wall (time-series optimized, much smaller than B-tree)
    op.execute(
        """
        CREATE INDEX idx_ticks_ts_wall_brin ON market_ticks
        USING BRIN (ts_wall)
        """
    )

    # 2. Composite B-tree index on (market_slug, outcome, ts_wall DESC)
    # For efficient "latest tick per market/outcome" queries
    op.create_index(
        "idx_ticks_market_outcome_time",
        "market_ticks",
        ["market_slug", "outcome", sa.text("ts_wall DESC")],
        unique=False,
    )

    # 3. B-tree index on event_id (for traceability, partial index to save space)
    op.create_index(
        "idx_ticks_event_id",
        "market_ticks",
        ["event_id"],
        unique=False,
        postgresql_where=sa.text("event_id IS NOT NULL"),
    )


def downgrade() -> None:
    """Drop market_ticks table and indexes."""
    # Drop indexes first
    op.drop_index("idx_ticks_event_id", table_name="market_ticks")
    op.drop_index("idx_ticks_market_outcome_time", table_name="market_ticks")
    op.execute("DROP INDEX IF EXISTS idx_ticks_ts_wall_brin")

    # Drop table
    op.drop_table("market_ticks")
