"""add_platform_tables_strategies_execution_control_live_strategy_activation_control_commands

Revision ID: 669d44032370
Revises: 2544c4bd05f5
Create Date: 2026-01-22 18:20:57.442696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "669d44032370"
down_revision: str | Sequence[str] | None = "2544c4bd05f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_control",
        sa.Column("id", sa.Integer(), nullable=False, comment="Singleton ID (always 1)"),
        sa.Column(
            "execution_enabled",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether live execution is enabled",
        ),
        sa.Column(
            "version",
            sa.Integer(),
            server_default="1",
            nullable=False,
            comment="Version for optimistic concurrency control",
        ),
        sa.Column(
            "updated_by",
            sa.String(length=255),
            nullable=False,
            comment="User/system that made the update",
        ),
        sa.Column("reason", sa.Text(), nullable=False, comment="Reason for the update"),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Update timestamp",
        ),
        sa.CheckConstraint("id = 1", name="execution_control_singleton_check"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "strategies",
        sa.Column(
            "strategy_id",
            sa.String(length=100),
            nullable=False,
            comment="Unique strategy identifier",
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Human-readable strategy name"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Strategy description"),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Strategy configuration (JSONB)",
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Whether strategy is enabled",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Record update timestamp",
        ),
        sa.PrimaryKeyConstraint("strategy_id"),
    )
    op.create_table(
        "control_commands",
        sa.Column(
            "command_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique command identifier (UUID)",
        ),
        sa.Column(
            "command_type",
            sa.String(length=50),
            nullable=False,
            comment=(
                "Command type: enable_execution, disable_execution, "
                "add_active_strategy, remove_active_strategy"
            ),
        ),
        sa.Column(
            "strategy_id",
            sa.String(length=100),
            nullable=True,
            comment="Strategy identifier (nullable for enable/disable commands)",
        ),
        sa.Column(
            "client_request_id",
            sa.String(length=255),
            nullable=True,
            comment="Client request ID for idempotency (nullable)",
        ),
        sa.Column(
            "expected_version",
            sa.Integer(),
            nullable=True,
            comment="Expected version for optimistic concurrency control",
        ),
        sa.Column("reason", sa.Text(), nullable=False, comment="Reason for the command"),
        sa.Column(
            "issued_by",
            sa.String(length=255),
            nullable=False,
            comment="User/system that issued the command",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
            comment="Command status: pending, applied, failed",
        ),
        sa.Column(
            "error_message", sa.Text(), nullable=True, comment="Error message if command failed"
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Command creation timestamp",
        ),
        sa.Column(
            "applied_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Timestamp when command was applied",
        ),
        sa.CheckConstraint(
            (
                "command_type IN ('enable_execution', 'disable_execution', "
                "'add_active_strategy', 'remove_active_strategy')"
            ),
            name="control_commands_command_type_check",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'applied', 'failed')", name="control_commands_status_check"
        ),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.strategy_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("command_id"),
    )
    # Create partial index for pending commands
    op.execute(
        """
        CREATE INDEX idx_control_commands_pending
        ON control_commands(status)
        WHERE status = 'pending'
        """
    )
    op.create_table(
        "live_strategy_activation",
        sa.Column(
            "strategy_id",
            sa.String(length=100),
            nullable=False,
            comment="Strategy identifier (FK to strategies.strategy_id)",
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether strategy is active for live trading",
        ),
        sa.Column(
            "activated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Timestamp when strategy was activated",
        ),
        sa.Column(
            "activated_by",
            sa.String(length=255),
            nullable=True,
            comment="User/system that activated the strategy",
        ),
        sa.Column("reason", sa.Text(), nullable=True, comment="Reason for activation"),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Record update timestamp",
        ),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.strategy_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("strategy_id"),
    )
    # Create partial index for active strategies
    op.execute(
        """
        CREATE INDEX idx_live_strategy_active
        ON live_strategy_activation(active)
        WHERE active = true
        """
    )
    # Create unique index for idempotency (with COALESCE for NULL strategy_id)
    op.execute(
        """
        CREATE UNIQUE INDEX idx_control_commands_idempotency
        ON control_commands(command_type, COALESCE(strategy_id, ''), client_request_id)
        WHERE client_request_id IS NOT NULL
        """
    )
    # Insert initial execution_control row
    op.execute(
        """
        INSERT INTO execution_control (id, execution_enabled, updated_by, reason, version)
        VALUES (1, false, 'system', 'Initial state: execution disabled by default', 1)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_control_commands_idempotency", table_name="control_commands")
    op.drop_index("idx_live_strategy_active", table_name="live_strategy_activation")
    op.drop_table("live_strategy_activation")
    op.drop_index("idx_control_commands_pending", table_name="control_commands")
    op.drop_table("control_commands")
    op.drop_table("strategies")
    op.drop_table("execution_control")
    # ### end Alembic commands ###
