from dataclasses import dataclass
from typing import Literal

Outcome = Literal["UP", "DOWN"]
Side = Literal["BUY", "SELL"]


@dataclass(frozen=True)
class MarketTick:
    """Market data tick with bid/ask prices.

    Attributes:
        ts: Unix timestamp in seconds (float for precision)
        market_slug: Market identifier (e.g., market slug)
        outcome: Market outcome ("UP" or "DOWN")
        best_bid: Best bid price (what buyers offer, from side=SELL)
        best_ask: Best ask price (what sellers ask, from side=BUY)
    """

    ts: float
    market_slug: str
    outcome: Outcome
    best_bid: float
    best_ask: float

    @property
    def mid(self) -> float:
        """Mid-market price (average of bid and ask)."""
        return (self.best_bid + self.best_ask) / 2.0

    @property
    def spread(self) -> float:
        """Bid-ask spread."""
        return self.best_ask - self.best_bid


@dataclass(frozen=True)
class TradeProposal:
    """Trade proposal generated by a trading model.

    Attributes:
        ts: Unix timestamp in seconds (float for precision) when proposal was created
        market_slug: Market identifier (e.g., market slug)
        outcome: Market outcome ("UP" or "DOWN")
        side: Trade side ("BUY" or "SELL")
        target_price: Target price for the trade (e.g., expected exit price)
        limit_price: Limit price for order execution (best_ask for BUY, best_bid for SELL)
        size: Trade size in USD
        reason: Human-readable reason for the proposal
        ttl_s: Time-to-live in seconds before proposal expires (default: 2.0)
    """

    ts: float
    market_slug: str
    outcome: Outcome
    side: Side
    target_price: float
    limit_price: float
    size: float
    reason: str
    ttl_s: float = 2.0


@dataclass(frozen=True)
class Order:
    """Executed order from OrderManager.

    Attributes:
        ts: Unix timestamp in seconds (float for precision) when order was executed
        market_slug: Market identifier (e.g., market slug)
        outcome: Market outcome ("UP" or "DOWN")
        side: Trade side ("BUY" or "SELL")
        size: Trade size in USD
        proposal_reason: Original reason from the trade proposal
        response: Order response from the CLOB API
    """

    ts: float
    market_slug: str
    outcome: Outcome
    side: Side
    size: float
    proposal_reason: str
    response: dict
