from typing import Literal

from pydantic import Field

from polytrader.events.types import Event, EventSource

Outcome = Literal["UP", "DOWN"]
Side = Literal["BUY", "SELL"]


class MarketDataEvent(Event):
    """Market data event from the Market Data Plant (MDP).

    Represents a snapshot of the order book for a specific market outcome.
    This is the canonical representation of market data in the system.

    Attributes:
        market_slug: Polymarket market identifier (e.g., "btc-updown-15m-1767900600")
        outcome: Market outcome ("UP" or "DOWN")
        best_bid: Best bid price (highest price buyers are willing to pay)
        best_ask: Best ask price (lowest price sellers are willing to accept)

    Note:
        - Timestamps come from Event base class (ts_wall, ts_mono)
        - Source is automatically set to EventSource.MDP
        - All Event base class fields are inherited (event_id, correlation_id, run_id, etc.)
    """

    source: EventSource = Field(default=EventSource.MDP)

    market_slug: str = Field(description="Polymarket market identifier")
    outcome: Outcome = Field(description="Market outcome: UP or DOWN")
    best_bid: float = Field(gt=0, le=1, description="Best bid price (0-1 range)")
    best_ask: float = Field(gt=0, le=1, description="Best ask price (0-1 range)")

    @property
    def mid(self) -> float:
        """Mid-market price (average of bid and ask).

        This is the fair value estimate between bid and ask.
        """
        return (self.best_bid + self.best_ask) / 2.0

    @property
    def spread(self) -> float:
        """Bid-ask spread (ask - bid).

        Represents the cost of immediate execution (liquidity cost).
        """
        return self.best_ask - self.best_bid

    @property
    def spread_bps(self) -> float:
        """Bid-ask spread in basis points (10000 * spread).

        Useful for comparing liquidity across different price levels.
        """
        return self.spread * 10000


class TradeProposal:
    """Trade proposal generated by a trading model.

    Attributes:
        ts: Unix timestamp in seconds (float for precision) when proposal was created
        market_slug: Market identifier (e.g., market slug)
        outcome: Market outcome ("UP" or "DOWN")
        side: Trade side ("BUY" or "SELL")
        target_price: Target price for the trade (e.g., expected exit price)
        limit_price: Limit price for order execution (best_ask for BUY, best_bid for SELL)
        size: Trade size in USD
        reason: Human-readable reason for the proposal
        ttl_s: Time-to-live in seconds before proposal expires (default: 2.0)
    """

    def __init__(
        self,
        ts: float,
        market_slug: str,
        outcome: Outcome,
        side: Side,
        target_price: float,
        limit_price: float,
        size: float,
        reason: str,
        ttl_s: float = 2.0,
    ) -> None:
        """Initialize TradeProposal."""
        self.ts = ts
        self.market_slug = market_slug
        self.outcome = outcome
        self.side = side
        self.target_price = target_price
        self.limit_price = limit_price
        self.size = size
        self.reason = reason
        self.ttl_s = ttl_s


class Order:
    """Executed order from OrderManager.

    Attributes:
        ts: Unix timestamp in seconds (float for precision) when order was executed
        market_slug: Market identifier (e.g., market slug)
        outcome: Market outcome ("UP" or "DOWN")
        side: Trade side ("BUY" or "SELL")
        size: Trade size in USD
        target_price: Target price for position (from proposal, None for SELL orders)
        proposal_reason: Original reason from the trade proposal
        response: Order response from the CLOB API
    """

    def __init__(
        self,
        ts: float,
        market_slug: str,
        outcome: Outcome,
        side: Side,
        size: float,
        target_price: float | None,
        proposal_reason: str,
        response: dict,
    ) -> None:
        """Initialize Order."""
        self.ts = ts
        self.market_slug = market_slug
        self.outcome = outcome
        self.side = side
        self.size = size
        self.target_price = target_price
        self.proposal_reason = proposal_reason
        self.response = response


class Position:
    """Active trading position.

    Attributes:
        market_slug: Market identifier
        outcome: Outcome ("UP" or "DOWN")
        size: Position size in USD
        target_price: Target price to sell at
        entry_price: Price when position was opened
        entry_time: Timestamp when position was opened
        order_id: ID of the BUY order that opened this position
    """

    def __init__(
        self,
        market_slug: str,
        outcome: Outcome,
        size: float,
        target_price: float,
        entry_price: float,
        entry_time: float,
        order_id: str | None = None,
    ) -> None:
        """Initialize Position."""
        self.market_slug = market_slug
        self.outcome = outcome
        self.size = size
        self.target_price = target_price
        self.entry_price = entry_price
        self.entry_time = entry_time
        self.order_id = order_id


class MarketChangeEvent:
    """Event published when market transitions.

    Attributes:
        old_market: Previous market slug (None if initial)
        new_market: New market slug
        timestamp: When transition occurred
    """

    def __init__(
        self,
        old_market: str | None,
        new_market: str,
        timestamp: float,
    ) -> None:
        """Initialize MarketChangeEvent."""
        self.old_market = old_market
        self.new_market = new_market
        self.timestamp = timestamp
