from typing import Literal

from pydantic import Field

from polytrader.events.types import Event, EventSource

Outcome = Literal["UP", "DOWN"]
Side = Literal["BUY", "SELL"]


class MarketDataEvent(Event):
    """Market data event from the Market Data Plant (MDP).

    Represents a snapshot of the order book for a specific market outcome.
    This is the canonical representation of market data in the system.

    Attributes:
        market_slug: Polymarket market identifier (e.g., "btc-updown-15m-1767900600")
        outcome: Market outcome ("UP" or "DOWN")
        best_bid: Best bid price (highest price buyers are willing to pay)
        best_ask: Best ask price (lowest price sellers are willing to accept)

    Note:
        - Timestamps come from Event base class (ts_wall, ts_mono)
        - Source is automatically set to EventSource.MDP
        - All Event base class fields are inherited (event_id, correlation_id, run_id, etc.)
    """

    source: EventSource = Field(default=EventSource.MDP)

    market_slug: str = Field(description="Polymarket market identifier")
    outcome: Outcome = Field(description="Market outcome: UP or DOWN")
    best_bid: float = Field(gt=0, le=1, description="Best bid price (0-1 range)")
    best_ask: float = Field(gt=0, le=1, description="Best ask price (0-1 range)")

    @property
    def mid(self) -> float:
        """Mid-market price (average of bid and ask).

        This is the fair value estimate between bid and ask.
        """
        return (self.best_bid + self.best_ask) / 2.0

    @property
    def spread(self) -> float:
        """Bid-ask spread (ask - bid).

        Represents the cost of immediate execution (liquidity cost).
        """
        return self.best_ask - self.best_bid

    @property
    def spread_bps(self) -> float:
        """Bid-ask spread in basis points (10000 * spread).

        Useful for comparing liquidity across different price levels.
        """
        return self.spread * 10000


class OrderIntentEvent(Event):
    """Order intent event generated by portfolio construction.

    Represents an intent to place an order, generated by the portfolio
    construction layer (e.g., SimpleThresholdStrategy). This is the canonical
    representation of trading intents in the system.

    Attributes:
        market_slug: Polymarket market identifier
        outcome: Market outcome ("UP" or "DOWN")
        side: Trade side ("BUY" or "SELL")
        target_price: Target price for the trade (e.g., expected exit price)
        limit_price: Limit price for order execution (best_ask for BUY, best_bid for SELL)
        size: Trade size in USD
        reason: Human-readable reason for the intent
        ttl_s: Time-to-live in seconds before intent expires (default: 2.0)

    Note:
        - Timestamps come from Event base class (ts_wall, ts_mono)
        - Source is automatically set to EventSource.PORTFOLIO
        - All Event base class fields are inherited (event_id, correlation_id, run_id, etc.)
    """

    source: EventSource = Field(default=EventSource.PORTFOLIO)

    market_slug: str = Field(description="Polymarket market identifier")
    outcome: Outcome = Field(description="Market outcome: UP or DOWN")
    side: Side = Field(description="Trade side: BUY or SELL")
    target_price: float = Field(gt=0, le=1, description="Target price for the trade (0-1 range)")
    limit_price: float = Field(
        gt=0, le=1, description="Limit price for order execution (0-1 range)"
    )
    size: float = Field(gt=0, description="Trade size in USD")
    reason: str = Field(description="Human-readable reason for the intent")
    ttl_s: float = Field(
        default=2.0, gt=0, description="Time-to-live in seconds before intent expires"
    )


class OrderExecutedEvent(Event):
    """Order executed event from execution layer.

    Represents an order that has been executed by the ExecutionRouter.
    This is the canonical representation of executed orders in the system.
    Note: This event type may be deprecated in favor of OMS events (OrderAckEvent, FillEvent).

    Attributes:
        market_slug: Polymarket market identifier
        outcome: Market outcome ("UP" or "DOWN")
        side: Trade side ("BUY" or "SELL")
        size: Trade size in USD
        target_price: Target price for position (from intent, None for SELL orders)
        proposal_reason: Original reason from the order intent
        response: Order response from the CLOB API (dict with order_id, status, etc.)

    Note:
        - Timestamps come from Event base class (ts_wall, ts_mono)
        - Source is automatically set to EventSource.EXEC
        - All Event base class fields are inherited (event_id, correlation_id, run_id, etc.)
    """

    source: EventSource = Field(default=EventSource.EXEC)

    market_slug: str = Field(description="Polymarket market identifier")
    outcome: Outcome = Field(description="Market outcome: UP or DOWN")
    side: Side = Field(description="Trade side: BUY or SELL")
    size: float = Field(gt=0, description="Trade size in USD")
    target_price: float | None = Field(
        default=None,
        ge=0,
        le=1,
        description="Target price for position (from intent, None for SELL orders)",
    )
    proposal_reason: str = Field(description="Original reason from the order intent")
    response: dict = Field(description="Order response from the CLOB API")


class Position:
    """Active trading position.

    Attributes:
        market_slug: Market identifier
        outcome: Outcome ("UP" or "DOWN")
        size: Position size in USD
        target_price: Target price to sell at
        entry_price: Price when position was opened
        entry_time: Timestamp when position was opened
        order_id: ID of the BUY order that opened this position
    """

    def __init__(
        self,
        market_slug: str,
        outcome: Outcome,
        size: float,
        target_price: float,
        entry_price: float,
        entry_time: float,
        order_id: str | None = None,
    ) -> None:
        """Initialize Position."""
        self.market_slug = market_slug
        self.outcome = outcome
        self.size = size
        self.target_price = target_price
        self.entry_price = entry_price
        self.entry_time = entry_time
        self.order_id = order_id


class MarketChangeEvent(Event):
    """Event published when market transitions.

    Represents a transition from one market to another, typically when
    a market expires and a new one becomes active. This is an operational
    event that triggers component lifecycle changes.

    Attributes:
        old_market: Previous market slug (None if initial market)
        new_market: New market slug (required)

    Note:
        - Timestamps come from Event base class (ts_wall, ts_mono)
        - Source is automatically set to EventSource.OPS
        - All Event base class fields are inherited (event_id, correlation_id, run_id, etc.)
    """

    source: EventSource = Field(default=EventSource.OPS)

    old_market: str | None = Field(
        default=None, description="Previous market slug (None if initial)"
    )
    new_market: str = Field(description="New market slug")


# Rebuild event models that depend on types defined here
# This ensures forward references are resolved after types are loaded
# We use a lazy import to avoid circular dependency
def _rebuild_dependent_models() -> None:
    """Rebuild event models that depend on types defined in this module."""
    try:
        # Lazy import to avoid circular dependency
        # Import the module, not the function directly
        import polytrader.events.types as events_types

        # Call the rebuild function
        events_types.rebuild_event_models()
    except (ImportError, AttributeError):
        # Events module not available yet or function doesn't exist
        pass


# Rebuild dependent models after types are defined
# This will succeed if events/types.py was already imported
_rebuild_dependent_models()
