/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to activate strategy for live trading.
 */
export interface ActivateStrategyRequest {
    /**
     * Reason for activation
     */
    'reason': string;
    /**
     * User/system issuing the command
     */
    'issued_by': string;
    /**
     * Client request ID for idempotency
     */
    'client_request_id': string;
}

