/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Single closed trade for strategy performance API.  Per proposal-past-performance-tab: One row per StrategyClosedTradeEvent. entry_time/exit_time are monotonic timestamps; exit_ts_wall is wall-clock for display.
 */
export interface ClosedTradeItem {
    /**
     * Market identifier
     */
    'market_slug': string;
    /**
     * Outcome traded
     */
    'outcome': ClosedTradeItemOutcomeEnum;
    /**
     * Entry time (monotonic)
     */
    'entry_time': number;
    /**
     * Exit time (monotonic)
     */
    'exit_time': number;
    /**
     * Exit wall-clock time (UTC)
     */
    'exit_ts_wall': string;
    /**
     * Average entry price
     */
    'entry_price': number;
    /**
     * Exit fill/settlement price (0 allowed for binary settlement)
     */
    'exit_price': number;
    /**
     * Position size in USD
     */
    'size': number;
    /**
     * Realized P&L in USD
     */
    'pnl': number;
    /**
     * Realized P&L as percentage
     */
    'pnl_pct': number;
    /**
     * WIN if pnl > 0, LOSS if pnl < 0, BREAKEVEN if pnl == 0
     */
    'result': ClosedTradeItemResultEnum;
    /**
     * Paper or live execution
     */
    'execution_mode': ClosedTradeItemExecutionModeEnum;
    /**
     * Trade duration (exit_time - entry_time) in seconds
     */
    'duration_seconds': number;
}

export const ClosedTradeItemOutcomeEnum = {
    Up: 'UP',
    Down: 'DOWN'
} as const;

export type ClosedTradeItemOutcomeEnum = typeof ClosedTradeItemOutcomeEnum[keyof typeof ClosedTradeItemOutcomeEnum];
export const ClosedTradeItemResultEnum = {
    Win: 'WIN',
    Loss: 'LOSS',
    Breakeven: 'BREAKEVEN'
} as const;

export type ClosedTradeItemResultEnum = typeof ClosedTradeItemResultEnum[keyof typeof ClosedTradeItemResultEnum];
export const ClosedTradeItemExecutionModeEnum = {
    Paper: 'paper',
    Live: 'live'
} as const;

export type ClosedTradeItemExecutionModeEnum = typeof ClosedTradeItemExecutionModeEnum[keyof typeof ClosedTradeItemExecutionModeEnum];


