/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Command envelope response (standardized for all commands).
 */
export interface CommandEnvelopeResponse {
    /**
     * Command identifier (UUID)
     */
    'command_id': string;
    /**
     * Command status
     */
    'status': CommandEnvelopeResponseStatusEnum;
    /**
     * Command submission timestamp
     */
    'submitted_at': string;
    /**
     * Related resource links
     */
    'links'?: { [key: string]: string; };
}

export const CommandEnvelopeResponseStatusEnum = {
    Pending: 'pending',
    Applied: 'applied',
    Failed: 'failed'
} as const;

export type CommandEnvelopeResponseStatusEnum = typeof CommandEnvelopeResponseStatusEnum[keyof typeof CommandEnvelopeResponseStatusEnum];


