/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Command status response.
 */
export interface CommandStatusResponse {
    /**
     * Command identifier (UUID)
     */
    'command_id': string;
    /**
     * Command type
     */
    'type': CommandStatusResponseTypeEnum;
    /**
     * Command status
     */
    'status': CommandStatusResponseStatusEnum;
    'error_message'?: string | null;
    /**
     * Command creation timestamp
     */
    'created_at': string;
    'applied_at'?: string | null;
    /**
     * Reason for the command
     */
    'reason': string;
    /**
     * User/system that issued the command
     */
    'issued_by': string;
}

export const CommandStatusResponseTypeEnum = {
    EnableExecution: 'enable_execution',
    DisableExecution: 'disable_execution',
    AddActiveStrategy: 'add_active_strategy',
    RemoveActiveStrategy: 'remove_active_strategy',
    KillSwitchActivate: 'kill_switch_activate',
    KillSwitchReset: 'kill_switch_reset'
} as const;

export type CommandStatusResponseTypeEnum = typeof CommandStatusResponseTypeEnum[keyof typeof CommandStatusResponseTypeEnum];
export const CommandStatusResponseStatusEnum = {
    Pending: 'pending',
    Applied: 'applied',
    Failed: 'failed'
} as const;

export type CommandStatusResponseStatusEnum = typeof CommandStatusResponseStatusEnum[keyof typeof CommandStatusResponseStatusEnum];


