/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VersionSelectorRequest } from './version-selector-request';

/**
 * Request to create a new strategy.  Per Commit 14: CreateStrategyRequest includes version_selector and desired_state instead of enabled boolean.
 */
export interface CreateStrategyRequest {
    /**
     * Strategy identifier
     */
    'strategy_id': string;
    /**
     * Human-readable strategy name
     */
    'name': string;
    'description'?: string | null;
    /**
     * Strategy configuration (JSONB)
     */
    'config': { [key: string]: any; };
    /**
     * Template type identifier (e.g., \'simple_threshold\')
     */
    'template_type_id': string;
    /**
     * Version selector (exact version or channel)
     */
    'version_selector': VersionSelectorRequest;
    /**
     * Desired lifecycle state (default: STOPPED)
     */
    'desired_state'?: CreateStrategyRequestDesiredStateEnum;
}

export const CreateStrategyRequestDesiredStateEnum = {
    Stopped: 'STOPPED',
    Starting: 'STARTING',
    Running: 'RUNNING',
    Paused: 'PAUSED',
    Draining: 'DRAINING',
    Stopping: 'STOPPING',
    Error: 'ERROR'
} as const;

export type CreateStrategyRequestDesiredStateEnum = typeof CreateStrategyRequestDesiredStateEnum[keyof typeof CreateStrategyRequestDesiredStateEnum];


