/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Standard error response.
 */
export interface ErrorResponse {
    /**
     * Error message
     */
    'error': string;
    'detail'?: string | null;
    'code'?: string | null;
}

