/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Execution control state response.
 */
export interface ExecutionStateResponse {
    /**
     * Whether execution is enabled
     */
    'execution_enabled': boolean;
    /**
     * Version for optimistic concurrency
     */
    'version': number;
    /**
     * Last update timestamp
     */
    'updated_at': string;
    /**
     * User/system that made the update
     */
    'updated_by': string;
    /**
     * Reason for the update
     */
    'reason': string;
}

