/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HealthGates } from './health-gates';

/**
 * System health response with gates.
 */
export interface HealthResponse {
    /**
     * Overall status (worst gate status)
     */
    'overall': HealthResponseOverallEnum;
    /**
     * Individual gate statuses
     */
    'gates': HealthGates;
}

export const HealthResponseOverallEnum = {
    Ok: 'ok',
    Degraded: 'degraded',
    Down: 'down'
} as const;

export type HealthResponseOverallEnum = typeof HealthResponseOverallEnum[keyof typeof HealthResponseOverallEnum];


