/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HealthGateStatus } from './health-gate-status';

/**
 * All health gates status.
 */
export interface HealthGates {
    /**
     * Database connectivity
     */
    'db': HealthGateStatus;
    /**
     * Market data staleness check
     */
    'market_data_freshness': HealthGateStatus;
    /**
     * Event bus processing lag
     */
    'event_bus_lag': HealthGateStatus;
    /**
     * Venue API connectivity
     */
    'venue_connectivity': HealthGateStatus;
    /**
     * Risk engine health
     */
    'risk_engine': HealthGateStatus;
    /**
     * Clock skew in milliseconds
     */
    'clock_skew_ms': number;
}

