/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MarketTickResponse } from './market-tick-response';

/**
 * Historical ticks response.  For a 15-minute market window, all ticks should fit in a single response. Use from_ts/to_ts to narrow the time range if needed.
 */
export interface HistoricalTicksResponse {
    /**
     * List of ticks (ordered by ts_wall)
     */
    'ticks': Array<MarketTickResponse>;
    /**
     * Number of ticks returned
     */
    'count': number;
}

