/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to reset (deactivate) the kill switch.  Resetting the kill switch does NOT re-enable execution — the operator must explicitly re-enable execution separately. This is a safety measure to prevent accidental re-enablement.
 */
export interface KillSwitchResetRequest {
    /**
     * Reason for resetting kill switch
     */
    'reason': string;
    /**
     * User/system resetting the kill switch
     */
    'issued_by'?: string;
}

