/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to activate the kill switch (emergency stop).  Per flows.mdc §13: Kill switch provides immediate stop-trading policy. Activating the kill switch immediately disables execution and emits KillSwitchEvent. This is a direct-apply action, not queued.
 */
export interface KillSwitchRequest {
    /**
     * Reason for activating kill switch
     */
    'reason': string;
    /**
     * Whether to cancel open orders when kill switch is activated
     */
    'cancel_open_orders'?: boolean;
    /**
     * User/system activating the kill switch
     */
    'issued_by'?: string;
}

