/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Market information response.  Represents a market/outcome pair with latest tick timestamp and active status.
 */
export interface MarketInfoResponse {
    /**
     * Market identifier
     */
    'market_slug': string;
    /**
     * Market outcome: UP or DOWN
     */
    'outcome': string;
    'latest_tick_ts': string | null;
    /**
     * Whether market is currently active (current window)
     */
    'active': boolean;
}

