/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One row per strategy instance — aggregated closed-trade performance.
 */
export interface PerformanceOverviewItemResponse {
    /**
     * Strategy instance identifier
     */
    'strategy_id': string;
    /**
     * Human-readable strategy name
     */
    'name': string;
    /**
     * Strategy template type
     */
    'template_type_id': string;
    /**
     * Strategy template version
     */
    'template_version': string;
    /**
     * Current lifecycle state
     */
    'actual_state': string;
    /**
     * Number of closed trades in window
     */
    'trade_count': number;
    /**
     * Number of winning trades
     */
    'wins': number;
    /**
     * Number of losing trades
     */
    'losses': number;
    /**
     * Number of breakeven trades
     */
    'breakevens': number;
    /**
     * Sum of realized P&L (USD)
     */
    'total_realized_pnl': number;
    'avg_trade_pnl'?: number | null;
    'win_rate_pct'?: number | null;
    'profit_factor'?: number | null;
    'last_trade_exit_ts_wall'?: string | null;
    /**
     * Evidence quality tier
     */
    'evidence_tier': PerformanceOverviewItemResponseEvidenceTierEnum;
}

export const PerformanceOverviewItemResponseEvidenceTierEnum = {
    InsufficientData: 'INSUFFICIENT_DATA',
    Tracking: 'TRACKING'
} as const;

export type PerformanceOverviewItemResponseEvidenceTierEnum = typeof PerformanceOverviewItemResponseEvidenceTierEnum[keyof typeof PerformanceOverviewItemResponseEvidenceTierEnum];


