/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PerformanceOverviewItemResponse } from './performance-overview-item-response';

/**
 * Aggregated performance across all strategy instances.  Per proposal §7.3: Response includes resolved timestamps, evidence threshold, and per-strategy aggregates.
 */
export interface PerformanceOverviewResponse {
    'from_ts_wall': string | null;
    /**
     * Resolved upper bound (UTC)
     */
    'to_ts_wall': string;
    'execution_mode'?: string | null;
    /**
     * Threshold used for evidence tier computation
     */
    'min_trades_threshold': number;
    /**
     * Per-strategy performance aggregates
     */
    'items': Array<PerformanceOverviewItemResponse>;
}

