/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Reproducibility metadata response.  Per Commit 14: RunIdentityResponse exposes reproducibility metadata for strategy instances, enabling deterministic replay.  Attributes:     template_code_ref: Git SHA / build artifact digest of template code     config_hash: SHA256 hash of config (for reproducibility)     dependency_set: Versions of key libs / model artifacts     market_data_snapshot_ref: Market data stream ID / snapshot reference
 */
export interface RunIdentityResponse {
    'template_code_ref'?: string | null;
    /**
     * SHA256 hash of config (for reproducibility)
     */
    'config_hash': string;
    'dependency_set'?: { [key: string]: string; } | null;
    'market_data_snapshot_ref'?: string | null;
}

