/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Single order record for strategy-scoped orders API.  Mirrors OrderCreatedEvent + intent (order_id, ts_wall, market, side, size, status). execution_mode indicates paper vs live so UI can show Paper/Live badge.
 */
export interface StrategyOrderItem {
    /**
     * Internal order UUID
     */
    'order_id': string;
    /**
     * Idempotency key
     */
    'client_order_id': string;
    /**
     * Wall-clock time (UTC, ISO 8601)
     */
    'ts_wall': string;
    /**
     * Market identifier
     */
    'market_slug': string;
    /**
     * Trade side: BUY or SELL
     */
    'side': string;
    /**
     * Order size in USD
     */
    'size': number;
    /**
     * Limit price (0-1 range)
     */
    'limit_price': number;
    /**
     * Order status (e.g. PENDING_SUBMIT, LIVE, FILLED, REJECTED)
     */
    'status': string;
    /**
     * Paper or live execution; UI shows Paper/Live badge
     */
    'execution_mode': StrategyOrderItemExecutionModeEnum;
}

export const StrategyOrderItemExecutionModeEnum = {
    Paper: 'paper',
    Live: 'live'
} as const;

export type StrategyOrderItemExecutionModeEnum = typeof StrategyOrderItemExecutionModeEnum[keyof typeof StrategyOrderItemExecutionModeEnum];


