/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Single signal record for strategy-scoped signals API.  Mirrors SignalEvent fields (event_id, ts_wall, market, scores).
 */
export interface StrategySignalItem {
    /**
     * Event identifier (UUID)
     */
    'event_id': string;
    /**
     * Wall-clock time (UTC, ISO 8601)
     */
    'ts_wall': string;
    /**
     * Market identifier
     */
    'market_slug': string;
    /**
     * Outcome: UP or DOWN
     */
    'outcome': string;
    /**
     * Probability UP wins
     */
    'p_up': number;
    /**
     * Probability DOWN wins
     */
    'p_down': number;
    /**
     * Edge/confidence score
     */
    'edge': number;
    /**
     * Confidence level
     */
    'confidence': number;
    /**
     * Strategy/model identifier
     */
    'model_id': string;
    /**
     * Model version
     */
    'model_version': string;
    'snapshot_hash'?: string | null;
    'rationale'?: string | null;
}

