/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Strategy template type response.  Per Commit 14: StrategyTypeResponse exposes strategy template information for discovery and selection.  Attributes:     type_id: Template type identifier (e.g., \'simple_threshold\')     name: Human-readable template name     description: Template description     available_versions: List of available versions     parameter_schema: OpenAPI-compatible parameter schema
 */
export interface StrategyTypeResponse {
    /**
     * Template type identifier (e.g., \'simple_threshold\')
     */
    'type_id': string;
    /**
     * Human-readable template name
     */
    'name': string;
    /**
     * Template description
     */
    'description': string;
    /**
     * List of available versions
     */
    'available_versions': Array<string>;
    /**
     * OpenAPI-compatible parameter schema
     */
    'parameter_schema': { [key: string]: any; };
}

