/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunIdentityResponse } from './run-identity-response';

/**
 * Strategy registry entry response.  Per Commit 14: StrategyResponse includes all new fields for template reference, lifecycle state, and reproducibility metadata.
 */
export interface StrategyResponse {
    /**
     * Strategy identifier
     */
    'strategy_id': string;
    /**
     * Human-readable strategy name
     */
    'name': string;
    'description'?: string | null;
    /**
     * Strategy configuration (JSONB)
     */
    'config': { [key: string]: any; };
    /**
     * Template type identifier (e.g., \'simple_threshold\')
     */
    'template_type_id': string;
    /**
     * Resolved template version (e.g., \'1.0.0\')
     */
    'template_version': string;
    /**
     * Desired lifecycle state (STOPPED | STARTING | RUNNING | etc.)
     */
    'desired_state': StrategyResponseDesiredStateEnum;
    /**
     * Actual runtime state (STOPPED | STARTING | RUNNING | etc.)
     */
    'actual_state': StrategyResponseActualStateEnum;
    'last_transition_at'?: string | null;
    'last_error'?: string | null;
    'run_identity'?: RunIdentityResponse | null;
    'deployment_id'?: string | null;
    'run_id'?: string | null;
    /**
     * Creation timestamp
     */
    'created_at': string;
    /**
     * Last update timestamp
     */
    'updated_at': string;
    /**
     * Whether strategy is enabled (derived from desired_state == RUNNING).
     */
    'enabled': boolean;
}

export const StrategyResponseDesiredStateEnum = {
    Stopped: 'STOPPED',
    Starting: 'STARTING',
    Running: 'RUNNING',
    Paused: 'PAUSED',
    Draining: 'DRAINING',
    Stopping: 'STOPPING',
    Error: 'ERROR'
} as const;

export type StrategyResponseDesiredStateEnum = typeof StrategyResponseDesiredStateEnum[keyof typeof StrategyResponseDesiredStateEnum];
export const StrategyResponseActualStateEnum = {
    Stopped: 'STOPPED',
    Starting: 'STARTING',
    Running: 'RUNNING',
    Paused: 'PAUSED',
    Draining: 'DRAINING',
    Stopping: 'STOPPING',
    Error: 'ERROR'
} as const;

export type StrategyResponseActualStateEnum = typeof StrategyResponseActualStateEnum[keyof typeof StrategyResponseActualStateEnum];


