/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to update an existing strategy.  Per Commit 14: UpdateStrategyRequest includes desired_state instead of enabled boolean.
 */
export interface UpdateStrategyRequest {
    'name'?: string | null;
    'description'?: string | null;
    'config'?: { [key: string]: any; } | null;
    'desired_state'?: UpdateStrategyRequestDesiredStateEnum | null;
}

export const UpdateStrategyRequestDesiredStateEnum = {
    Stopped: 'STOPPED',
    Starting: 'STARTING',
    Running: 'RUNNING',
    Paused: 'PAUSED',
    Draining: 'DRAINING',
    Stopping: 'STOPPING',
    Error: 'ERROR'
} as const;

export type UpdateStrategyRequestDesiredStateEnum = typeof UpdateStrategyRequestDesiredStateEnum[keyof typeof UpdateStrategyRequestDesiredStateEnum];


