/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VersionSelectorRequest } from './version-selector-request';

/**
 * Request to validate a strategy configuration.  Per Commit 16: ValidateStrategyConfigRequest allows clients to validate configurations before creating strategy instances.  Attributes:     template_type_id: Template type identifier (e.g., \'simple_threshold\')     version_selector: Version selector (exact version or channel)     config: Configuration dictionary to validate
 */
export interface ValidateStrategyConfigRequest {
    /**
     * Template type identifier (e.g., \'simple_threshold\')
     */
    'template_type_id': string;
    /**
     * Version selector (exact version or channel)
     */
    'version_selector': VersionSelectorRequest;
    /**
     * Strategy configuration to validate
     */
    'config': { [key: string]: any; };
}

