/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response from strategy configuration validation.  Per Commit 16: ValidateStrategyConfigResponse provides validation results with clear error messages and warnings.  Attributes:     valid: Whether the configuration is valid     errors: List of validation error messages (empty if valid)     warnings: List of validation warnings (optional issues)     template_type_id: Template type identifier used for validation     template_version: Resolved template version used for validation
 */
export interface ValidateStrategyConfigResponse {
    /**
     * Whether the configuration is valid
     */
    'valid': boolean;
    /**
     * List of validation error messages
     */
    'errors'?: Array<string>;
    /**
     * List of validation warnings (optional issues)
     */
    'warnings'?: Array<string>;
    /**
     * Template type identifier used for validation
     */
    'template_type_id': string;
    /**
     * Resolved template version used for validation
     */
    'template_version': string;
}

