/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Version conflict error response (409 Conflict).
 */
export interface VersionConflictResponse {
    'error'?: string;
    /**
     * Version that was expected
     */
    'expected_version': number;
    /**
     * Current version
     */
    'actual_version': number;
    /**
     * Explanation of the version conflict
     */
    'detail': string;
}

