/* tslint:disable */
/* eslint-disable */
/**
 * Polytrader Control API
 * Control plane API for Polytrader platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Version selector request model.  Per Commit 14: VersionSelectorRequest allows clients to specify either an exact version or a channel selector for strategy templates.  Attributes:     exact: Exact version string (e.g., \"1.2.3\") or None     channel: Channel name (\"stable\", \"beta\", \"dev\") or None     major: Major version number for channel selection (e.g., 1) or None
 */
export interface VersionSelectorRequest {
    'exact'?: string | null;
    'channel'?: VersionSelectorRequestChannelEnum | null;
    'major'?: number | null;
}

export const VersionSelectorRequestChannelEnum = {
    Stable: 'stable',
    Beta: 'beta',
    Dev: 'dev'
} as const;

export type VersionSelectorRequestChannelEnum = typeof VersionSelectorRequestChannelEnum[keyof typeof VersionSelectorRequestChannelEnum];


